name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build123:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script asjdkksdhdjsdl
        run: echo Hello, world!
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: '3.13' 
      - name: hello.py
        run: python hello.py
